services:
  nginx:
    image: nginx:stable
    container_name: servidor-http
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/frontend:/usr/share/nginx/html:ro
      - /home/ubuntu/docker/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
